import Link from "next/link"
import { ArrowLeft } from "lucide-react"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The rules and guidelines governing use of our platform.",
}

const sections: Array<{ heading: string; body: React.ReactNode }> = [
  {
    heading: "1 · Acceptance of terms",
    body: (
      <p>
        By accessing or using the AIMerge platform and The Inner Light
        Experience (&quot;Service&quot;), operated by TetraNoodle Technologies
        (&quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;), you agree to be bound by these
        Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, do
        not use the Service.
      </p>
    ),
  },
  {
    heading: "2 · Description of service",
    body: (
      <p>
        AIMerge provides an AI-powered self-reflection experience called The
        Inner Light Experience. The Service asks users a series of questions
        and uses artificial intelligence to generate personalised reflections
        based on their answers. The Service is designed for personal insight
        and self-reflection purposes only.
      </p>
    ),
  },
  {
    heading: "3 · Eligibility",
    body: (
      <p>
        You must be at least 18 years of age to use this Service. By using
        the Service, you represent and warrant that you are at least 18
        years old and have the legal capacity to enter into these Terms.
      </p>
    ),
  },
  {
    heading: "4 · User accounts and data",
    body: (
      <>
        <p>
          To use the Service, you provide your first name and email address.
          You agree to:
        </p>
        <ul className="mt-3 list-disc space-y-1 pl-6 marker:text-foreground/40">
          <li>Provide accurate and complete information</li>
          <li>Not impersonate another person or entity</li>
          <li>Not use the Service for any unlawful purpose</li>
          <li>Not attempt to gain unauthorised access to any part of the Service</li>
        </ul>
      </>
    ),
  },
  {
    heading: "5 · Acceptable use",
    body: (
      <>
        <p>You agree not to use the Service to:</p>
        <ul className="mt-3 list-disc space-y-1 pl-6 marker:text-foreground/40">
          <li>Submit false, misleading, or fraudulent information</li>
          <li>Harass, abuse, or harm others</li>
          <li>Interfere with or disrupt the Service or its infrastructure</li>
          <li>Attempt to reverse engineer, decompile, or extract source code</li>
          <li>Use automated systems (bots, scrapers) without prior written consent</li>
          <li>Violate any applicable local, state, national, or international law</li>
        </ul>
      </>
    ),
  },
  {
    heading: "6 · AI-generated content",
    body: (
      <>
        <p>
          The Service generates content using artificial intelligence. You
          acknowledge and agree that:
        </p>
        <ul className="mt-3 list-disc space-y-2 pl-6 marker:text-foreground/40">
          <li>
            <span className="text-ink">Not professional advice -</span>{" "}
            AI-generated reflections are for personal insight only. They do
            not constitute medical, psychological, legal, financial, or any
            other form of professional advice.
          </li>
          <li>
            <span className="text-ink">No guarantees -</span> we do not
            guarantee the accuracy, completeness, or usefulness of any
            AI-generated content.
          </li>
          <li>
            <span className="text-ink">Personal responsibility -</span> you
            are solely responsible for any decisions or actions you take
            based on the content generated by the Service.
          </li>
          <li>
            <span className="text-ink">Variability -</span> AI outputs may
            vary and are not deterministic.
          </li>
        </ul>
      </>
    ),
  },
  {
    heading: "7 · Intellectual property",
    body: (
      <>
        <p>
          All content, features, and functionality of the Service - text,
          graphics, logos, icons, software, and the underlying technology -
          are owned by or licensed to the Company and are protected by
          copyright, trademark, and other intellectual property laws.
        </p>
        <p className="mt-3">
          You retain ownership of the responses you submit. By using the
          Service, you grant us a limited, non-exclusive license to process
          your responses for the purpose of generating your personalised
          reflections, and to allow authorised members of the AIMerge team to
          review your responses and AI-generated outputs to enhance your
          experience, personalise follow-up, calibrate the diagnostic, and
          ensure quality and safety. Such review is governed by the
          confidentiality commitments described in our{" "}
          <Link
            href="/privacy"
            className="text-ink underline-offset-4 hover:underline"
          >
            Privacy Policy
          </Link>
          .
        </p>
      </>
    ),
  },
  {
    heading: "8 · Privacy",
    body: (
      <p>
        Your use of the Service is also governed by our{" "}
        <Link href="/privacy" className="text-ink underline-offset-4 hover:underline">
          Privacy Policy
        </Link>
        , which is incorporated into these Terms by reference.
      </p>
    ),
  },
  {
    heading: "9 · Disclaimers",
    body: (
      <>
        <p>
          THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT
          WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
          LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
          PURPOSE, AND NON-INFRINGEMENT.
        </p>
        <p className="mt-3">
          We do not warrant that the Service will be uninterrupted,
          error-free, or free of harmful components. We do not warrant that
          AI-generated content will meet your expectations or requirements.
        </p>
      </>
    ),
  },
  {
    heading: "10 · Limitation of liability",
    body: (
      <>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT
          SHALL THE COMPANY OR ITS DIRECTORS, EMPLOYEES, PARTNERS, AGENTS,
          OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
          CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS,
          DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:
        </p>
        <ul className="mt-3 list-disc space-y-1 pl-6 marker:text-foreground/40">
          <li>Your access to or use of (or inability to access or use) the Service</li>
          <li>Any content obtained from the Service, including AI-generated reflections</li>
          <li>Unauthorised access, use, or alteration of your data</li>
          <li>Any other matter relating to the Service</li>
        </ul>
      </>
    ),
  },
  {
    heading: "11 · Indemnification",
    body: (
      <p>
        You agree to defend, indemnify, and hold harmless the Company and
        its officers, directors, employees, and agents from and against any
        claims, liabilities, damages, losses, and expenses (including
        reasonable attorneys&apos; fees) arising out of or related to your
        use of the Service, your violation of these Terms, or your violation
        of any rights of a third party.
      </p>
    ),
  },
  {
    heading: "12 · Termination",
    body: (
      <p>
        We reserve the right to suspend or terminate your access to the
        Service at any time, without notice, for any reason, including a
        violation of these Terms. Upon termination, your right to use the
        Service will cease immediately. Provisions that by their nature
        should survive termination shall survive.
      </p>
    ),
  },
  {
    heading: "13 · Modifications to terms",
    body: (
      <p>
        We reserve the right to modify these Terms at any time. Changes will
        be effective immediately upon posting. Your continued use of the
        Service after modifications constitutes acceptance of the revised
        Terms.
      </p>
    ),
  },
  {
    heading: "14 · Governing law",
    body: (
      <p>
        These Terms shall be governed by and construed in accordance with
        the laws of the jurisdiction in which the Company is incorporated,
        without regard to its conflict of law provisions.
      </p>
    ),
  },
  {
    heading: "15 · Severability",
    body: (
      <p>
        If any provision of these Terms is found to be unenforceable or
        invalid, that provision will be limited or eliminated to the
        minimum extent necessary, and the remaining provisions will remain
        in full force and effect.
      </p>
    ),
  },
  {
    heading: "16 · Entire agreement",
    body: (
      <p>
        These Terms, together with the Privacy Policy, constitute the entire
        agreement between you and the Company regarding your use of the
        Service and supersede all prior agreements.
      </p>
    ),
  },
  {
    heading: "17 · Contact us",
    body: (
      <>
        <p>
          If you have questions about these Terms of Service, please contact
          us at:
        </p>
        <p className="mt-3 font-serif text-ink">
          AIMerge - a TetraNoodle Technologies product
          <br />
          <span className="font-serif-italic text-foreground/85">
            sales@tetranoodle.com
          </span>
        </p>
      </>
    ),
  },
]

export default function TermsOfServicePage() {
  return (
    <div
      data-palette="marine"
      className="min-h-screen bg-background font-sans text-foreground"
    >
      <div className="mx-auto max-w-3xl px-5 py-20 sm:px-8 sm:py-28">
        <Link
          href="/"
          className="mb-12 inline-flex items-center gap-1.5 text-[11px] uppercase tracking-[0.22em] text-foreground/65 transition-colors hover:text-ink"
        >
          <ArrowLeft className="h-3.5 w-3.5" strokeWidth={1.5} />
          Back to home
        </Link>

        <p className="eyebrow mb-5 text-foreground/70">
          <span className="pulse-dot mr-3" aria-hidden />
          Quiet pages
        </p>

        <h1 className="font-serif text-[40px] leading-[1.05] text-ink sm:text-[48px]">
          Terms of
          <span className="block font-serif-italic text-foreground">service.</span>
        </h1>

        <p className="mt-4 text-[12px] uppercase tracking-[0.22em] text-foreground/55">
          Last updated · April 10, 2026
        </p>

        <div className="hairline mt-12" />

        <article className="mt-12 space-y-12 text-[15.5px] leading-[1.85] text-foreground/85">
          {sections.map((s) => (
            <section key={s.heading}>
              <h2 className="mb-4 font-serif text-[22px] leading-snug text-ink">
                {s.heading}
              </h2>
              {s.body}
            </section>
          ))}
        </article>

        <div className="hairline mt-16" />
        <p className="mt-6 font-serif-italic text-[13px] text-foreground/55">
          Composed quietly. Read at your own pace.
        </p>
      </div>
    </div>
  )
}
